import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FinanceProvider } from "./context/FinanceContext";
import { prisma } from "@/lib/prisma";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const [categories, transactions] = await Promise.all([
    prisma.category.findMany(),
    prisma.transaction.findMany(),
  ]);

  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <FinanceProvider
          initialCategories={categories.map((category) => ({
            id: category.id,
            name: category.name,
            amount: category.budget,
            used: 0,
            color: category.color,
            emoji: category.emoji,
          }))}
          initialTransactions={transactions.map((transaction) => ({
            id: transaction.id,
            amount: transaction.amount,
            type: transaction.type as 'expense',
            categoryId: transaction.categoryId,
            date: transaction.date.toISOString().slice(0, 10)
          }))}
        >
          {children}
        </FinanceProvider>
      </body>
    </html>
  );
}
